language: erlang
otp_release:
   - 18.0
   - 18.1

sudo: false

addons:
  apt:
    packages:
      - build-essential

script:
  - "make"
  - "make tests"

# notifications:
#   email:
#     recipients:
#       - 
#     on_success: change
#     on_failure: always
